name: npm-publish-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        name: Set up Node.js
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Setup Node Environment
        run: npm ci

      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to NPMJS.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
